set -s set-clipboard on
set -g history-limit 10000
set -g mouse on
set -g mode-keys vi
set -g status-keys vi
set -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'