services:
  subtitle-builder-server:
    image: ghcr.io/tuanitfdev/subtitle-builder-server:${APP_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      # cache_from:
      #   - type=gha
      # cache_to:
      #   - type=gha,mode=max
    container_name: subtitle_builder_server_container
    # Cấu hình quan trọng nhất để nhận diện GPU NVIDIA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ports:
      - "1111:1111"
      # - "8080:8080"
      # - "8384:8384"
      # - "6006:6006"
      - "8000:8000"
    # Mount thư mục hiện tại vào container để dev không cần build lại liên tục
    volumes:
      - .:/opt/ws
      # - ./supervisor/script/instance_portal.sh:/opt/supervisor-scripts/instance_portal.sh
      # - ./supervisor/script/tensorboard.sh:/opt/supervisor-scripts/tensorboard.sh
      # - ./supervisor/script/tunnel_manager.sh:/opt/supervisor-scripts/tunnel_manager.sh
      # - ./supervisor/script/jupyter.sh:/opt/supervisor-scripts/jupyter.sh
      # - ./supervisor/script/syncthing.sh:/opt/supervisor-scripts/syncthing.sh
    # Sử dụng file .env cho biến môi trường
    # env_file:
    #   - .env
    # Giữ container chạy ngầm (tương đương -it)
    stdin_open: true
    tty: true
    # Lệnh mặc định khi start
    # command: /bin/bash
