[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
user=root
logfile=/app/data/log/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info
pidfile=/tmp/supervisord.pid

[program:app]
command=python src/mainServer.py
directory=/app
autostart=true
autorestart=true
startsecs=15
startretries=3
stdout_logfile=/app/data/log/app.stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
redirect_stderr=true

[program:appLog]
command=tail --retry -f /app/data/log/app.stdout.log
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0