[program:app]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/app.sh
directory=/opt/ws/app
stopasgroup=true
killasgroup=true
autostart=true
autorestart=true
startsecs=3
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true