[program:app]
command=/opt/supervisor-scripts/app.sh
directory=/opt/app
autostart=true
autorestart=true
startsecs=15
startretries=3
stdout_logfile=/opt/app/data/log/app.stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
redirect_stderr=true

[program:appLog]
command=tail --retry -f /opt/app/data/log/app.stdout.log
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0